import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'dev-sim',
  description: 'Generated by dev-sim',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header className="text-2xl text-center">
          Dev-Sim
        </header>
        <nav className="flex flex-row flex-wrap justify-center gap-2 text-sm text-stone-900 m-4">
          
          <div>
            <Link href="/health">건강관리</Link>
          </div>
          <div>
            <Link href="/coloring">우리아이색칠공부</Link>
          </div>
          <div>
            <Link href="/signup">회원가입</Link>
          </div>
          <div>
            <Link href="/login">로그인</Link>
          </div>
        </nav>
        <main className="m-11">
          {children}
        </main>
        
      </body>
    </html>
  )
}
